### ISSUE TITLE
Error with remote version is much newer: v1.24.0

### ISSUE THREAD

**Issue by AlekseiGP** [nvtienanh/hyperv-k8s#1]
Thanks for great scripts, but I am unable to execute "Initialize-Kubeadm".
I tried to modify Powershell script and change download version of kubectl.exe from 1.22 to 1.24, but it did not help. Could you help, please?
I tried to replace `https://dl.k8s.io/release/v1.22.0/bin/windows/amd64/kubectl.exe` with `https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/windows/amd64/kubectl.exe` . And tried to change variable `$kubeversion = '1.22.1-00'`  to `$kubeversion = '1.24.0'` .

```
[hyperv]: PS C:\Users\Administrator\Documents> .\hyperv-k8s.ps1 Initialize-Kubeadm

executing on master: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 && \
      mkdir -p $HOME/.kube && \
      sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config && \
      sudo chown $(id -u):$(id -g) $HOME/.kube/config && \
      kubectl apply -f $(eval echo https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
I0523 20:48:59.374989    5282 version.go:255] remote version is much newer: v1.24.0; falling back to: stable-1.22
    + CategoryInfo          : NotSpecified: (I0523 20:48:59....to: stable-1.22:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by nvtienanh** [comment]
@AlekseiGP Could you please try `$kubeversion = '1.24.0-00'`

**Comment by AlekseiGP** [comment]
> @AlekseiGP Could you please try `$kubeversion = '1.24.0-00'`
Same error :(
```
[hyperv]: PS C:\Users\Administrator\Documents> .\hyperv-k8s.ps1 Initialize-Kubeadm

executing on master: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 && \
      mkdir -p $HOME/.kube && \
      sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config && \
      sudo chown $(id -u):$(id -g) $HOME/.kube/config && \
      kubectl apply -f $(eval echo https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
I0524 08:28:14.562462   93336 version.go:255] remote version is much newer: v1.24.0; falling back to: stable-1.22
    + CategoryInfo          : NotSpecified: (I0524 08:28:14....to: stable-1.22:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
Maybe, problem with kubeadm inside ISO image also?

**Comment by AlekseiGP** [comment]
@nvtienanh , looks, i found solution! 
[Line 698](https://github.com/nvtienanh/hyperv-k8s/blob/9936a74b7b7c0c5af09022b25036e99a1cfc0d2e/hyperv-k8s.ps1#L698) contains  `sudo kubeadm init` . Kubeadm inside image is version 1.22.1, and current version is 1.24. I add parameter `--kubernetes-version=v1.22.1` to command line, and it works now!
Line 698 now is:
`    $init = "sudo kubeadm init --kubernetes-version=v1.22.1 --pod-network-cidr=$cninet && \`
